### ISSUE TITLE
set-env has been deprecated

### ISSUE THREAD

**Issue by kkrellwitz** [Azure/docker-login#18]
I recently received the following warning in the azure/docker-login@v1 action log

```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Can you update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions and update the action to use the new commands, so this action will continue to work before they stop supporting the set-env command.

**Comment by thesattiraju** [comment]
@kkrellwitz we're working on it.

cc: @shigupt202
