### ISSUE TITLE
Repo 'About' description needs updating

### ISSUE THREAD

**Issue by larryclaman** [Azure/docker-login#26]
This repo's 'About' description reads `Enable GitHub developers to deploy to Kubernetes service using GitHub Actions`.
This should be edited to reflect the docker content rather than Kubernetes.
(Sorry, I can't do a PR on the 'about' text or I'd do it myself. :) )

**Comment by ajinkya599** [comment]
Thanks @larryclaman  for pointing out!
I have fixed it.
