### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by oliwheeler** [Azure/docker-login#3]
Repo Steps:

1. Use azure/docker-login@master (commit [ed03ba4fc617589298156ade22efab93820817b0](https://github.com/Azure/docker-login/tree/ed03ba4fc617589298156ade22efab93820817b0)).
2. Observe error:
<img width="604" alt="azure-docker-login-error" src="https://user-images.githubusercontent.com/10214164/68900134-7bcd4c80-0733-11ea-92ce-40cbd4741555.png">

**Comment by alinnert** [comment]
The [documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#commit-and-push-your-action-to-github) explicitly states that you need to commit your `node_modules` folder as well.

I also stumbled over this. I can imagine this is **a)** because of performance and **b)** to make sure everyone uses the exact same dependencies, so the action will always work the same way.

**Comment by thesattiraju** [comment]
The `node_modules` are checked into the releases branch. You could use `azure/docker-login@v1` instead for your workflows. 
@RoopeshNair could you guide them about why we had to remove the node_modules from the master branch?

**Comment by RoopeshNair** [comment]
@alinnert The master branch has the latest code and is unstable to bind to since a breaking new major version may first get implemented in master.

**Comment by cjonasw** [comment]
You could just get the action to install the dependencies, granted it isn't as fast but at least you don't need to commit dependencies. This worked for me. NPM looks after making sure everyone has the correct dependency version; that's what the lock file is for.

**Comment by emmahsax** [comment]
@cjonasw How do I have the action load the dependencies? I'm assuming based on a `package-lock.json` file or something? I have an action that I've forked somebody else, and am making changes, and it's just too crazy to try to commit all of the `node_modules` all the time. Nobody else uses my fork (to my knowledge), and I'd like to do the auto-loading despite it potentially being a little slower.

[Here's my PR](https://github.com/emmasax4/github-pages-deploy-action/pull/20/checks?check_run_id=1371073471). Is there a code snippet or something I need to add to the main JS file?

---

EDIT: Oh, actually a little more googling found the answer, I believe! https://github.com/actions/typescript-action/issues/4#issuecomment-525019468 is the answer!

**Comment by xgqfrms** [comment]
> The [documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#commit-and-push-your-action-to-github) explicitly states that you need to commit your `node_modules` folder as well.
> 
> I also stumbled over this. I can imagine this is **a)** because of performance and **b)** to make sure everyone uses the exact same dependencies, so the action will always work the same way.

Do you mean not ignoring the `node_modules` folder when publishing your release?

why not install the dependencies, in your `action.yml` file

**Comment by alinnert** [comment]
@xgqfrms The structure of this `action.yml` file is different. The code doesn't get executed via `jobs` but via a `runs` property. You can also see this in the docs page I've linked. So you cannot add a `npm install` step before your code runs.

Also, this would make your action depend on npm. If npm is down your action doesn't work either. I can totally see why it has been done this way.
