### ISSUE TITLE
Use same secret AZURE_CREDENTIALS as Azure/login and Azure/aks-set-context

### ISSUE THREAD

**Issue by dkirrane** [Azure/docker-login#34]
Is there a way to use this Action with the same secret I created for  `Azure/login` and `Azure/aks-set-context` actions?

`creds: ${{ secrets.AZURE_CREDENTIALS }}`

**Comment by thesattiraju** [comment]
You cannot use it directly, but you can write an intermediate step to extract the SPN-ID and SPN-KEY into separate runtime variable, mask them explicitly and use them in this action. By feeding `SPN-ID` as the username and `SPN-KEY` as the password

**Comment by algattik** [comment]
I have published a working solution at https://cloudarchitected.com/2021/09/logging-into-acr-in-github-actions/

**Comment by jtomaszewski** [comment]
How about we make that a built-in feature into the docker-login action? WOuld you accept such a PR?
