### ISSUE TITLE
Can not use the new docker/login version v1.0.1

### ISSUE THREAD

**Issue by mike-petersen** [Azure/docker-login#48]
Since the new version a few minutes ago, we get the following error:

`node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/docker-login/v1/lib/login.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:[10](https://github.com/edeka-digital/crm-cougar/actions/runs/3522251858/jobs/5905272535#step:3:11)05:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/docker-login/v1/lib/login.js:13:14)
    at Module._compile (node:internal/modules/cjs/loader:[11](https://github.com/edeka-digital/crm-cougar/actions/runs/3522251858/jobs/5905272535#step:3:12)01:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/edeka-digital/crm-cougar/actions/runs/3522251858/jobs/5905272535#step:3:13))
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/azure/docker-login/v1/lib/login.js' ]
***`

**Comment by akbast** [comment]
We are also getting the same error

**Comment by amilochau** [comment]
Hi, I have seen the same issue on my projects for a few minutes. I would prefer not to have to explicitly reference v1.0.0 in all my workflows...

**Comment by thien-nguyenthanh** [comment]
Yes. I also getting the same issue with `azure/docker-login@v1`
Error:
`Error: Cannot find module '@actions/core'
`

**Comment by mike-petersen** [comment]
> Hi, I have seen the same issue on my projects for a few minutes. I would prefer not to have to explicitly reference v1.0.0 in all my workflows...

unfortunately the previous version is called only "v1". Due to that v1.0.0 does not even work :(

**Comment by bamarch** [comment]
> > Hi, I have seen the same issue on my projects for a few minutes. I would prefer not to have to explicitly reference v1.0.0 in all my workflows...
> 
> unfortunately the previous version is called only "v1". Due to that v1.0.0 does not even work :(


You can do @2faa66cfd1a1e8d02713b5df43a1f4da62872ec2

**Comment by antimirov** [comment]
Same error, started happening today

**Comment by ehovaere** [comment]
Anyone know what commit was tagged "v1" before one hour ago ?

**Comment by ehovaere** [comment]
Sorry just saw 2faa66cfd1a1e8d02713b5df43a1f4da62872ec2, thx @bamarch

**Comment by akbast** [comment]
I am getting the same error with 2fa...

```
Run azure/docker-login@2faa66cfd1a1e8d02713b5df43a1f4da62872ec2
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@actions/core'
```

**Comment by mike-petersen** [comment]
> > > Hi, I have seen the same issue on my projects for a few minutes. I would prefer not to have to explicitly reference v1.0.0 in all my workflows...
> > 
> > 
> > unfortunately the previous version is called only "v1". Due to that v1.0.0 does not even work :(
> 
> You can do @2faa66cfd1a1e8d02713b5df43a1f4da62872ec2

Unfortunately this also does not seem to work. If you look under tags https://github.com/Azure/docker-login/tags it seems like the v1 tag is now also updated to the broken version v1.0.1

**Comment by ChillyBots** [comment]
@BALAGA-GAYATRI Can you get eyes on this? quite likely to have broken a lot downstream

**Comment by ehovaere** [comment]
Ok, so my question is still valid :) 
Anyone know what commit was tagged "v1" before one hour ago ?

**Comment by akbast** [comment]
https://github.com/Azure/docker-login/commit/7c3fbb89c5162a802bc3743389996c6a647bd5db this worked for us.

**Comment by BALAGA-GAYATRI** [comment]
Can you please check now?

**Comment by bamarch** [comment]
> Anyone know what commit was tagged "v1" before one hour ago ?

Unclear what it was since the tags keep getting changed, seems like going back far enough in time is working:

https://github.com/Azure/docker-login/commit/7c3fbb89c5162a802bc3743389996c6a647bd5db

**Comment by bamarch** [comment]
> Can you please check now?

I've just ran using `@v1` and it works in my environment, thank you for the quick attention

**Comment by akbast** [comment]
v1 is working now.

**Comment by BALAGA-GAYATRI** [comment]
I have chacked v1.0.1 is also working now. Please re-run once and confirm

**Comment by mike-petersen** [comment]
> I have chacked v1.0.1 is also working now. Please re-run once and confirm

Thanks. Looks like it is fixed.
