### ISSUE TITLE
Node 16 is deprecated, move to node 20

### ISSUE THREAD

**Issue by eikooc** [Azure/docker-login#63]
# GitHub Actions: Transitioning from Node 16 to Node 20

> Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by chrisnruud** [comment]
👍

**Comment by peterbe** [comment]
https://github.com/Azure/docker-login/pull/64 FYI
Let's hope it gets released.

**Comment by lgmorand** [comment]
Thanks @peterbe. I did my part captain !
